"""Create all tables

Revision ID: b43596f28869
Revises: 
Create Date: 2025-11-16 15:27:42.143546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b43596f28869'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auteur',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de famille'),
    sa.Column('prenom', sa.String(length=255), nullable=True, comment='Prénom'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email de contact'),
    sa.Column('orcid', sa.String(length=19), nullable=True, comment='Identifiant ORCID (XXXX-XXXX-XXXX-XXXX)'),
    sa.Column('google_scholar_id', sa.String(length=50), nullable=True, comment='Identifiant Google Scholar'),
    sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True, comment='Identifiant Semantic Scholar (Phase 3 enrichissement)'),
    sa.Column('homepage_url', sa.String(length=500), nullable=True, comment='URL de la page personnelle'),
    sa.Column('h_index', sa.Integer(), nullable=False, comment='H-index (calculé via Semantic Scholar en Phase 3)'),
    sa.Column('nombre_publications', sa.Integer(), nullable=False, comment='Nombre de publications'),
    sa.Column('nombre_citations', sa.Integer(), nullable=False, comment='Nombre total de citations'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('h_index >= 0', name='check_auteur_h_index_positive'),
    sa.CheckConstraint('nombre_citations >= 0', name='check_auteur_citations_positive'),
    sa.CheckConstraint('nombre_publications >= 0', name='check_auteur_publications_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid')
    )
    op.create_index('idx_auteur_h_index', 'auteur', ['h_index'], unique=False, postgresql_ops={'h_index': 'DESC'})
    op.create_index('idx_auteur_nom_prenom', 'auteur', ['nom', 'prenom'], unique=False)
    op.create_index('idx_auteur_orcid', 'auteur', ['orcid'], unique=True, postgresql_where='orcid IS NOT NULL')
    op.create_index('idx_auteur_semantic_scholar', 'auteur', ['semantic_scholar_id'], unique=False)
    op.create_table('changement_metadonnees',
    sa.Column('entite_type', sa.String(length=100), nullable=False, comment="Type d'entité modifiée (Publication, Auteur, etc.)"),
    sa.Column('entite_id', sa.UUID(), nullable=False, comment="ID de l'entité modifiée"),
    sa.Column('champ_modifie', sa.String(length=255), nullable=False, comment='Nom du champ modifié'),
    sa.Column('ancienne_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ancienne valeur (format JSON)'),
    sa.Column('nouvelle_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Nouvelle valeur (format JSON)'),
    sa.Column('date_changement', sa.DateTime(), nullable=False, comment='Date et heure du changement'),
    sa.Column('utilisateur', sa.String(length=255), nullable=True, comment='Utilisateur ayant effectué le changement'),
    sa.Column('raison', sa.Text(), nullable=True, comment='Raison du changement (optionnel)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changement_date', 'changement_metadonnees', ['date_changement'], unique=False, postgresql_ops={'date_changement': 'DESC'})
    op.create_index('idx_changement_entite', 'changement_metadonnees', ['entite_type', 'entite_id'], unique=False)
    op.create_index('idx_changement_utilisateur', 'changement_metadonnees', ['utilisateur'], unique=False)
    op.create_table('impact_societal',
    sa.Column('titre', sa.String(length=500), nullable=False, comment="Titre de l'impact identifié"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description détaillée de l'impact"),
    sa.Column('type_impact', sa.Enum('SOCIAL', 'ECONOMIC', 'ENVIRONMENTAL', 'ETHICAL', 'POLITICAL', 'HEALTH', 'EDUCATION', 'OTHER', name='typeimpactenum'), nullable=False, comment="Type d'impact sociétal"),
    sa.Column('niveau_impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='niveauimpactenum'), nullable=False, comment="Niveau de gravité/importance de l'impact"),
    sa.Column('domaine', sa.String(length=255), nullable=True, comment="Domaine d'application (santé, finance, etc.)"),
    sa.Column('date_identification', sa.Date(), nullable=True, comment="Date d'identification de l'impact"),
    sa.Column('source', sa.String(length=500), nullable=True, comment="Source de l'analyse d'impact"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_domaine', 'impact_societal', ['domaine'], unique=False)
    op.create_index('idx_impact_niveau', 'impact_societal', ['niveau_impact'], unique=False)
    op.create_index('idx_impact_type', 'impact_societal', ['type_impact'], unique=False)
    op.create_table('licence',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de la licence'),
    sa.Column('type_licence', sa.Enum('OPEN_SOURCE', 'PROPRIETARY', 'CREATIVE_COMMONS', 'MIT', 'APACHE', 'GPL', 'BSD', 'OTHER', name='typelicenceenum'), nullable=False, comment='Type de licence'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description de la licence'),
    sa.Column('url', sa.Text(), nullable=True, comment='URL vers le texte complet de la licence'),
    sa.Column('is_open_source', sa.Boolean(), nullable=False, comment='Indique si la licence est open source'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('metrique_engagement',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de la métrique'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Description de la métrique'),
    sa.Column('type_metrique', sa.Enum('VIEWS', 'DOWNLOADS', 'CITATIONS', 'STARS', 'FORKS', 'MENTIONS', 'SHARES', 'OTHER', name='typemetriqueenum'), nullable=False, comment="Type de métrique d'engagement"),
    sa.Column('source_metrique', sa.String(length=255), nullable=True, comment='Source de la métrique (arXiv, GitHub, etc.)'),
    sa.Column('date_collecte', sa.Date(), nullable=False, comment='Date de collecte de la métrique'),
    sa.Column('valeur', sa.Integer(), nullable=False, comment='Valeur numérique de la métrique'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('valeur >= 0', name='check_metrique_valeur_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrique_date', 'metrique_engagement', ['date_collecte'], unique=False)
    op.create_index('idx_metrique_source', 'metrique_engagement', ['source_metrique'], unique=False)
    op.create_index('idx_metrique_type', 'metrique_engagement', ['type_metrique'], unique=False)
    op.create_table('organisation',
    sa.Column('nom', sa.String(length=255), nullable=False, comment="Nom complet de l'organisation"),
    sa.Column('nom_court', sa.String(length=100), nullable=True, comment='Acronyme ou nom court'),
    sa.Column('type_organisation', sa.Enum('UNIVERSITY', 'COMPANY', 'RESEARCH_CENTER', 'THINK_TANK', 'GOVERNMENT', 'NGO', 'OTHER', name='typeorganisationenum'), nullable=False, comment="Type d'organisation"),
    sa.Column('pays', sa.String(length=3), nullable=True, comment='Code pays ISO 3166-1 alpha-3'),
    sa.Column('ville', sa.String(length=255), nullable=True, comment='Ville'),
    sa.Column('secteur', sa.String(length=255), nullable=True, comment="Secteur d'activité"),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL du site web'),
    sa.Column('ranking_mondial', sa.Integer(), nullable=True, comment='Classement mondial (si applicable)'),
    sa.Column('nombre_publications', sa.Integer(), nullable=False, comment='Nombre de publications associées'),
    sa.Column('nombre_chercheurs', sa.Integer(), nullable=False, comment='Nombre de chercheurs affiliés'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('nombre_chercheurs >= 0', name='check_org_chercheurs_positive'),
    sa.CheckConstraint('nombre_publications >= 0', name='check_org_publications_positive'),
    sa.CheckConstraint('ranking_mondial > 0', name='check_org_ranking_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organisation_nom', 'organisation', ['nom'], unique=False)
    op.create_index('idx_organisation_pays', 'organisation', ['pays'], unique=False)
    op.create_index('idx_organisation_ranking', 'organisation', ['ranking_mondial'], unique=False)
    op.create_index('idx_organisation_type', 'organisation', ['type_organisation'], unique=False)
    op.create_table('source',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de la source'),
    sa.Column('nom_court', sa.String(length=100), nullable=True, comment='Acronyme ou nom court'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description de la source'),
    sa.Column('url', sa.Text(), nullable=True, comment='URL du site web de la source'),
    sa.Column('nombre_publications', sa.Integer(), nullable=False, comment='Nombre de publications de cette source'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('nombre_publications >= 0', name='check_source_publications_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('theme',
    sa.Column('label', sa.String(length=255), nullable=False, comment='Nom du thème'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description du thème'),
    sa.Column('niveau_hierarchie', sa.Integer(), nullable=False, comment="Profondeur dans l'arbre (0 = racine)"),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='ID du thème parent'),
    sa.Column('chemin_hierarchie', sa.Text(), nullable=True, comment="Chemin complet (ex: 'AI/ML/Deep Learning')"),
    sa.Column('nombre_publications', sa.Integer(), nullable=False, comment='Nombre de publications associées'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('niveau_hierarchie >= 0 AND niveau_hierarchie <= 10', name='check_theme_niveau_valid'),
    sa.CheckConstraint('nombre_publications >= 0', name='check_theme_publications_positive'),
    sa.ForeignKeyConstraint(['parent_id'], ['theme.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_theme_chemin', 'theme', ['chemin_hierarchie'], unique=False, postgresql_using='gin', postgresql_ops={'chemin_hierarchie': 'gin_trgm_ops'})
    op.create_index('idx_theme_label', 'theme', ['label'], unique=False)
    op.create_index('idx_theme_niveau', 'theme', ['niveau_hierarchie'], unique=False)
    op.create_index('idx_theme_parent_id', 'theme', ['parent_id'], unique=False)
    op.create_table('affiliation',
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False, comment="Date de début de l'affiliation"),
    sa.Column('date_fin', sa.Date(), nullable=True, comment='Date de fin (NULL = toujours en poste)'),
    sa.Column('poste', sa.String(length=255), nullable=True, comment='Poste occupé'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('date_fin IS NULL OR date_fin >= date_debut', name='check_affiliation_dates_valid'),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('auteur_id', 'organisation_id', 'date_debut')
    )
    op.create_index('idx_affiliation_active', 'affiliation', ['auteur_id'], unique=False, postgresql_where='date_fin IS NULL')
    op.create_index('idx_affiliation_auteur', 'affiliation', ['auteur_id'], unique=False)
    op.create_index('idx_affiliation_dates', 'affiliation', ['date_debut', 'date_fin'], unique=False)
    op.create_index('idx_affiliation_organisation', 'affiliation', ['organisation_id'], unique=False)
    op.create_table('auteur_metrique',
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.Column('metrique_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metrique_id'], ['metrique_engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auteur_id', 'metrique_id')
    )
    op.create_index('idx_auteur_metrique_auteur', 'auteur_metrique', ['auteur_id'], unique=False)
    op.create_index('idx_auteur_metrique_metrique', 'auteur_metrique', ['metrique_id'], unique=False)
    op.create_table('collaboration',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de la collaboration'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description de la collaboration'),
    sa.Column('type_collaboration', sa.Enum('RESEARCH', 'INDUSTRIAL', 'ACADEMIC', 'INTERNATIONAL', 'PUBLIC_PRIVATE', 'OTHER', name='typecollaborationenum'), nullable=False, comment='Type de collaboration'),
    sa.Column('organisation_principale_id', sa.UUID(), nullable=False, comment='Organisation principale'),
    sa.Column('date_debut', sa.Date(), nullable=False, comment='Date de début de la collaboration'),
    sa.Column('date_fin', sa.Date(), nullable=True, comment='Date de fin (NULL = en cours)'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL du site web de la collaboration'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('date_fin IS NULL OR date_fin >= date_debut', name='check_collaboration_dates_valid'),
    sa.ForeignKeyConstraint(['organisation_principale_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collaboration_dates', 'collaboration', ['date_debut', 'date_fin'], unique=False)
    op.create_index('idx_collaboration_organisation', 'collaboration', ['organisation_principale_id'], unique=False)
    op.create_index('idx_collaboration_type', 'collaboration', ['type_collaboration'], unique=False)
    op.create_table('dataset',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom du dataset'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description du dataset'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL de téléchargement ou documentation'),
    sa.Column('taille', sa.String(length=50), nullable=True, comment="Taille du dataset (ex: '10GB', '1M samples')"),
    sa.Column('format', sa.String(length=100), nullable=True, comment='Format des données (CSV, JSON, HDF5, etc.)'),
    sa.Column('licence_id', sa.UUID(), nullable=True, comment='Licence du dataset'),
    sa.Column('organisation_id', sa.UUID(), nullable=True, comment='Organisation créatrice'),
    sa.Column('date_creation', sa.Date(), nullable=True, comment='Date de création du dataset'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['licence_id'], ['licence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dataset_licence', 'dataset', ['licence_id'], unique=False)
    op.create_index('idx_dataset_nom', 'dataset', ['nom'], unique=False)
    op.create_index('idx_dataset_organisation', 'dataset', ['organisation_id'], unique=False)
    op.create_table('evenement',
    sa.Column('nom', sa.String(length=255), nullable=False, comment="Nom de l'événement"),
    sa.Column('nom_complet', sa.String(length=500), nullable=True, comment="Nom complet de l'événement"),
    sa.Column('type_evenement', sa.Enum('CONFERENCE', 'WORKSHOP', 'SYMPOSIUM', 'SEMINAR', 'WEBINAR', 'HACKATHON', 'COMPETITION', 'OTHER', name='typeevenementenum'), nullable=False, comment="Type d'événement"),
    sa.Column('statut', sa.Enum('PLANNED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='statutevenementenum'), nullable=False, comment="Statut actuel de l'événement"),
    sa.Column('date_debut', sa.Date(), nullable=False, comment='Date de début'),
    sa.Column('date_fin', sa.Date(), nullable=True, comment='Date de fin'),
    sa.Column('lieu', sa.String(length=500), nullable=True, comment="Lieu physique de l'événement"),
    sa.Column('ville', sa.String(length=255), nullable=True, comment='Ville'),
    sa.Column('pays', sa.String(length=3), nullable=True, comment='Code pays ISO 3166-1 alpha-3'),
    sa.Column('url', sa.String(length=500), nullable=True, comment="URL du site web de l'événement"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description de l'événement"),
    sa.Column('organisation_principale_id', sa.UUID(), nullable=True, comment='Organisation organisatrice principale'),
    sa.Column('nombre_participants', sa.Integer(), nullable=False, comment='Nombre de participants'),
    sa.Column('nombre_publications', sa.Integer(), nullable=False, comment='Nombre de publications présentées'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('date_fin IS NULL OR date_fin >= date_debut', name='check_evenement_dates_valid'),
    sa.CheckConstraint('nombre_participants >= 0', name='check_evenement_participants_positive'),
    sa.CheckConstraint('nombre_publications >= 0', name='check_evenement_publications_positive'),
    sa.ForeignKeyConstraint(['organisation_principale_id'], ['organisation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evenement_date_debut', 'evenement', ['date_debut'], unique=False)
    op.create_index('idx_evenement_statut', 'evenement', ['statut'], unique=False)
    op.create_index('idx_evenement_type', 'evenement', ['type_evenement'], unique=False)
    op.create_table('outil',
    sa.Column('nom', sa.String(length=255), nullable=False, comment="Nom de l'outil"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description de l'outil"),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL du site web officiel'),
    sa.Column('github_url', sa.String(length=500), nullable=True, comment='URL du repository GitHub'),
    sa.Column('licence_id', sa.UUID(), nullable=True, comment="Licence de l'outil"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['licence_id'], ['licence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outil_licence', 'outil', ['licence_id'], unique=False)
    op.create_index('idx_outil_nom', 'outil', ['nom'], unique=False)
    op.create_table('technologie',
    sa.Column('nom', sa.String(length=255), nullable=False, comment='Nom de la technologie'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description de la technologie'),
    sa.Column('type_technologie', sa.Enum('ALGORITHM', 'FRAMEWORK', 'ARCHITECTURE', 'TECHNIQUE', 'TOOL', 'LIBRARY', 'PLATFORM', name='typetechnologieenum'), nullable=False, comment='Type de technologie'),
    sa.Column('theme_id', sa.UUID(), nullable=False, comment='Thème de recherche associé'),
    sa.Column('niveau_maturite', sa.Enum('RESEARCH', 'PROTOTYPE', 'PRODUCTION', 'MATURE', 'DEPRECATED', name='niveaumaturiteenum'), nullable=True, comment='Niveau de maturité technologique'),
    sa.Column('popularite', sa.Numeric(precision=5, scale=2), nullable=True, comment='Score de popularité'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL du site web officiel'),
    sa.Column('github_url', sa.String(length=500), nullable=True, comment='URL du repository GitHub'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_technologie_maturite', 'technologie', ['niveau_maturite'], unique=False)
    op.create_index('idx_technologie_nom', 'technologie', ['nom'], unique=False)
    op.create_index('idx_technologie_theme', 'technologie', ['theme_id'], unique=False)
    op.create_index('idx_technologie_type', 'technologie', ['type_technologie'], unique=False)
    op.create_table('collaboration_auteur',
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True, comment='Rôle dans la collaboration'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collaboration_id', 'auteur_id')
    )
    op.create_index('idx_collaboration_auteur_auteur', 'collaboration_auteur', ['auteur_id'], unique=False)
    op.create_index('idx_collaboration_auteur_collaboration', 'collaboration_auteur', ['collaboration_id'], unique=False)
    op.create_table('organisation_collaboration',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True, comment="Rôle de l'organisation dans la collaboration"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organisation_id', 'collaboration_id')
    )
    op.create_index('idx_organisation_collaboration_collaboration', 'organisation_collaboration', ['collaboration_id'], unique=False)
    op.create_index('idx_organisation_collaboration_organisation', 'organisation_collaboration', ['organisation_id'], unique=False)
    op.create_table('publication',
    sa.Column('titre', sa.String(length=500), nullable=False, comment='Titre de la publication'),
    sa.Column('abstract', sa.Text(), nullable=True, comment='Résumé/Abstract'),
    sa.Column('doi', sa.String(length=255), nullable=True, comment='Digital Object Identifier (CRITIQUE pour Semantic Scholar Phase 3)'),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True, comment='Identifiant arXiv (CRITIQUE Phase 3 - alternative au DOI)'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='URL de la publication'),
    sa.Column('date_publication', sa.Date(), nullable=False, comment='Date de publication'),
    sa.Column('type_publication', sa.Enum('ARTICLE', 'PREPRINT', 'CONFERENCE_PAPER', 'JOURNAL_PAPER', 'TUTORIAL', 'SURVEY', 'WORKSHOP_PAPER', 'THESIS', 'BOOK_CHAPTER', 'TECHNICAL_REPORT', 'OTHER', name='typepublicationenum'), nullable=False, comment='Type de publication'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PENDING_ENRICHMENT', 'ENRICHED', 'ENRICHMENT_FAILED', name='statuspublicationenum'), nullable=False, comment="Statut d'enrichissement (Phase 3 - pipeline)"),
    sa.Column('language', sa.String(length=10), nullable=True, comment='Code langue ISO 639-1'),
    sa.Column('source_nom', sa.String(length=100), nullable=True, comment='Nom de la source (arXiv, IEEE, ACM, etc.)'),
    sa.Column('evenement_id', sa.UUID(), nullable=True, comment='Événement associé (si conference/workshop paper)'),
    sa.Column('nombre_citations', sa.Integer(), nullable=False, comment='Nombre de citations (Phase 3 - Semantic Scholar)'),
    sa.Column('nombre_auteurs', sa.Integer(), nullable=False, comment="Nombre d'auteurs"),
    sa.Column('score_popularite', sa.Numeric(precision=5, scale=2), nullable=False, comment='Score de popularité calculé'),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Vecteur pour full-text search (généré automatiquement)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique UUID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('nombre_auteurs >= 0', name='check_publication_auteurs_positive'),
    sa.CheckConstraint('nombre_citations >= 0', name='check_publication_citations_positive'),
    sa.CheckConstraint('score_popularite >= 0', name='check_publication_score_positive'),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index('idx_publication_arxiv_id', 'publication', ['arxiv_id'], unique=False, postgresql_where='arxiv_id IS NOT NULL')
    op.create_index('idx_publication_citations', 'publication', ['nombre_citations'], unique=False, postgresql_ops={'nombre_citations': 'DESC'})
    op.create_index('idx_publication_date', 'publication', ['date_publication'], unique=False, postgresql_ops={'date_publication': 'DESC'})
    op.create_index('idx_publication_doi', 'publication', ['doi'], unique=True, postgresql_where='doi IS NOT NULL')
    op.create_index('idx_publication_search', 'publication', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_publication_source', 'publication', ['source_nom'], unique=False)
    op.create_index('idx_publication_status', 'publication', ['status'], unique=False)
    op.create_index('idx_publication_type', 'publication', ['type_publication'], unique=False)
    op.create_table('technologie_dataset',
    sa.Column('technologie_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technologie_id'], ['technologie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technologie_id', 'dataset_id')
    )
    op.create_index('idx_technologie_dataset_dataset', 'technologie_dataset', ['dataset_id'], unique=False)
    op.create_index('idx_technologie_dataset_technologie', 'technologie_dataset', ['technologie_id'], unique=False)
    op.create_table('technologie_outil',
    sa.Column('technologie_id', sa.UUID(), nullable=False),
    sa.Column('outil_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['outil_id'], ['outil.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technologie_id'], ['technologie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technologie_id', 'outil_id')
    )
    op.create_index('idx_technologie_outil_outil', 'technologie_outil', ['outil_id'], unique=False)
    op.create_index('idx_technologie_outil_technologie', 'technologie_outil', ['technologie_id'], unique=False)
    op.create_table('citation',
    sa.Column('publication_source_id', sa.UUID(), nullable=False, comment='Publication qui cite'),
    sa.Column('publication_cible_id', sa.UUID(), nullable=False, comment='Publication citée'),
    sa.Column('contexte', sa.Text(), nullable=True, comment='Contexte de la citation (extrait du texte)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('publication_source_id != publication_cible_id', name='check_citation_no_self_citation'),
    sa.ForeignKeyConstraint(['publication_cible_id'], ['publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_source_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_source_id', 'publication_cible_id')
    )
    op.create_index('idx_citation_cible', 'citation', ['publication_cible_id'], unique=False)
    op.create_index('idx_citation_source', 'citation', ['publication_source_id'], unique=False)
    op.create_table('publication_auteur',
    sa.Column('publication_id', sa.UUID(), nullable=False, comment='ID de la publication'),
    sa.Column('auteur_id', sa.UUID(), nullable=False, comment="ID de l'auteur"),
    sa.Column('ordre', sa.Integer(), nullable=False, comment="Position dans la liste d'auteurs (1 = premier)"),
    sa.Column('role', sa.String(length=50), nullable=True, comment="Rôle de l'auteur (first_author, corresponding_author, etc.)"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('ordre > 0', name='check_publication_auteur_ordre_positive'),
    sa.ForeignKeyConstraint(['auteur_id'], ['auteur.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'auteur_id'),
    sa.UniqueConstraint('publication_id', 'ordre', name='uq_publication_auteur_ordre')
    )
    op.create_index('idx_publication_auteur_auteur', 'publication_auteur', ['auteur_id'], unique=False)
    op.create_index('idx_publication_auteur_publication', 'publication_auteur', ['publication_id'], unique=False)
    op.create_table('publication_dataset',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'dataset_id')
    )
    op.create_index('idx_publication_dataset_dataset', 'publication_dataset', ['dataset_id'], unique=False)
    op.create_index('idx_publication_dataset_publication', 'publication_dataset', ['publication_id'], unique=False)
    op.create_table('publication_impact',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('impact_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['impact_id'], ['impact_societal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'impact_id')
    )
    op.create_index('idx_publication_impact_impact', 'publication_impact', ['impact_id'], unique=False)
    op.create_index('idx_publication_impact_publication', 'publication_impact', ['publication_id'], unique=False)
    op.create_table('publication_metrique',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('metrique_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['metrique_id'], ['metrique_engagement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'metrique_id')
    )
    op.create_index('idx_publication_metrique_metrique', 'publication_metrique', ['metrique_id'], unique=False)
    op.create_index('idx_publication_metrique_publication', 'publication_metrique', ['publication_id'], unique=False)
    op.create_table('publication_outil',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('outil_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['outil_id'], ['outil.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'outil_id')
    )
    op.create_index('idx_publication_outil_outil', 'publication_outil', ['outil_id'], unique=False)
    op.create_index('idx_publication_outil_publication', 'publication_outil', ['publication_id'], unique=False)
    op.create_table('publication_technologie',
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('technologie_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technologie_id'], ['technologie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'technologie_id')
    )
    op.create_index('idx_publication_technologie_publication', 'publication_technologie', ['publication_id'], unique=False)
    op.create_index('idx_publication_technologie_technologie', 'publication_technologie', ['technologie_id'], unique=False)
    op.create_table('publication_theme',
    sa.Column('publication_id', sa.UUID(), nullable=False, comment='ID de la publication'),
    sa.Column('theme_id', sa.UUID(), nullable=False, comment='ID du thème'),
    sa.Column('pertinence', sa.Numeric(precision=3, scale=2), nullable=False, comment='Score de pertinence (0.0 à 1.0, calculé par ML Phase 3)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification'),
    sa.CheckConstraint('pertinence >= 0 AND pertinence <= 1', name='check_publication_theme_pertinence_valid'),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'theme_id')
    )
    op.create_index('idx_publication_theme_pertinence', 'publication_theme', ['pertinence'], unique=False, postgresql_ops={'pertinence': 'DESC'})
    op.create_index('idx_publication_theme_publication', 'publication_theme', ['publication_id'], unique=False)
    op.create_index('idx_publication_theme_theme', 'publication_theme', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_publication_theme_theme', table_name='publication_theme')
    op.drop_index('idx_publication_theme_publication', table_name='publication_theme')
    op.drop_index('idx_publication_theme_pertinence', table_name='publication_theme', postgresql_ops={'pertinence': 'DESC'})
    op.drop_table('publication_theme')
    op.drop_index('idx_publication_technologie_technologie', table_name='publication_technologie')
    op.drop_index('idx_publication_technologie_publication', table_name='publication_technologie')
    op.drop_table('publication_technologie')
    op.drop_index('idx_publication_outil_publication', table_name='publication_outil')
    op.drop_index('idx_publication_outil_outil', table_name='publication_outil')
    op.drop_table('publication_outil')
    op.drop_index('idx_publication_metrique_publication', table_name='publication_metrique')
    op.drop_index('idx_publication_metrique_metrique', table_name='publication_metrique')
    op.drop_table('publication_metrique')
    op.drop_index('idx_publication_impact_publication', table_name='publication_impact')
    op.drop_index('idx_publication_impact_impact', table_name='publication_impact')
    op.drop_table('publication_impact')
    op.drop_index('idx_publication_dataset_publication', table_name='publication_dataset')
    op.drop_index('idx_publication_dataset_dataset', table_name='publication_dataset')
    op.drop_table('publication_dataset')
    op.drop_index('idx_publication_auteur_publication', table_name='publication_auteur')
    op.drop_index('idx_publication_auteur_auteur', table_name='publication_auteur')
    op.drop_table('publication_auteur')
    op.drop_index('idx_citation_source', table_name='citation')
    op.drop_index('idx_citation_cible', table_name='citation')
    op.drop_table('citation')
    op.drop_index('idx_technologie_outil_technologie', table_name='technologie_outil')
    op.drop_index('idx_technologie_outil_outil', table_name='technologie_outil')
    op.drop_table('technologie_outil')
    op.drop_index('idx_technologie_dataset_technologie', table_name='technologie_dataset')
    op.drop_index('idx_technologie_dataset_dataset', table_name='technologie_dataset')
    op.drop_table('technologie_dataset')
    op.drop_index('idx_publication_type', table_name='publication')
    op.drop_index('idx_publication_status', table_name='publication')
    op.drop_index('idx_publication_source', table_name='publication')
    op.drop_index('idx_publication_search', table_name='publication', postgresql_using='gin')
    op.drop_index('idx_publication_doi', table_name='publication', postgresql_where='doi IS NOT NULL')
    op.drop_index('idx_publication_date', table_name='publication', postgresql_ops={'date_publication': 'DESC'})
    op.drop_index('idx_publication_citations', table_name='publication', postgresql_ops={'nombre_citations': 'DESC'})
    op.drop_index('idx_publication_arxiv_id', table_name='publication', postgresql_where='arxiv_id IS NOT NULL')
    op.drop_table('publication')
    op.drop_index('idx_organisation_collaboration_organisation', table_name='organisation_collaboration')
    op.drop_index('idx_organisation_collaboration_collaboration', table_name='organisation_collaboration')
    op.drop_table('organisation_collaboration')
    op.drop_index('idx_collaboration_auteur_collaboration', table_name='collaboration_auteur')
    op.drop_index('idx_collaboration_auteur_auteur', table_name='collaboration_auteur')
    op.drop_table('collaboration_auteur')
    op.drop_index('idx_technologie_type', table_name='technologie')
    op.drop_index('idx_technologie_theme', table_name='technologie')
    op.drop_index('idx_technologie_nom', table_name='technologie')
    op.drop_index('idx_technologie_maturite', table_name='technologie')
    op.drop_table('technologie')
    op.drop_index('idx_outil_nom', table_name='outil')
    op.drop_index('idx_outil_licence', table_name='outil')
    op.drop_table('outil')
    op.drop_index('idx_evenement_type', table_name='evenement')
    op.drop_index('idx_evenement_statut', table_name='evenement')
    op.drop_index('idx_evenement_date_debut', table_name='evenement')
    op.drop_table('evenement')
    op.drop_index('idx_dataset_organisation', table_name='dataset')
    op.drop_index('idx_dataset_nom', table_name='dataset')
    op.drop_index('idx_dataset_licence', table_name='dataset')
    op.drop_table('dataset')
    op.drop_index('idx_collaboration_type', table_name='collaboration')
    op.drop_index('idx_collaboration_organisation', table_name='collaboration')
    op.drop_index('idx_collaboration_dates', table_name='collaboration')
    op.drop_table('collaboration')
    op.drop_index('idx_auteur_metrique_metrique', table_name='auteur_metrique')
    op.drop_index('idx_auteur_metrique_auteur', table_name='auteur_metrique')
    op.drop_table('auteur_metrique')
    op.drop_index('idx_affiliation_organisation', table_name='affiliation')
    op.drop_index('idx_affiliation_dates', table_name='affiliation')
    op.drop_index('idx_affiliation_auteur', table_name='affiliation')
    op.drop_index('idx_affiliation_active', table_name='affiliation', postgresql_where='date_fin IS NULL')
    op.drop_table('affiliation')
    op.drop_index('idx_theme_parent_id', table_name='theme')
    op.drop_index('idx_theme_niveau', table_name='theme')
    op.drop_index('idx_theme_label', table_name='theme')
    op.drop_index('idx_theme_chemin', table_name='theme', postgresql_using='gin', postgresql_ops={'chemin_hierarchie': 'gin_trgm_ops'})
    op.drop_table('theme')
    op.drop_table('source')
    op.drop_index('idx_organisation_type', table_name='organisation')
    op.drop_index('idx_organisation_ranking', table_name='organisation')
    op.drop_index('idx_organisation_pays', table_name='organisation')
    op.drop_index('idx_organisation_nom', table_name='organisation')
    op.drop_table('organisation')
    op.drop_index('idx_metrique_type', table_name='metrique_engagement')
    op.drop_index('idx_metrique_source', table_name='metrique_engagement')
    op.drop_index('idx_metrique_date', table_name='metrique_engagement')
    op.drop_table('metrique_engagement')
    op.drop_table('licence')
    op.drop_index('idx_impact_type', table_name='impact_societal')
    op.drop_index('idx_impact_niveau', table_name='impact_societal')
    op.drop_index('idx_impact_domaine', table_name='impact_societal')
    op.drop_table('impact_societal')
    op.drop_index('idx_changement_utilisateur', table_name='changement_metadonnees')
    op.drop_index('idx_changement_entite', table_name='changement_metadonnees')
    op.drop_index('idx_changement_date', table_name='changement_metadonnees', postgresql_ops={'date_changement': 'DESC'})
    op.drop_table('changement_metadonnees')
    op.drop_index('idx_auteur_semantic_scholar', table_name='auteur')
    op.drop_index('idx_auteur_orcid', table_name='auteur', postgresql_where='orcid IS NOT NULL')
    op.drop_index('idx_auteur_nom_prenom', table_name='auteur')
    op.drop_index('idx_auteur_h_index', table_name='auteur', postgresql_ops={'h_index': 'DESC'})
    op.drop_table('auteur')
    # ### end Alembic commands ###
